on:
  pull_request_target:
    branches: [ main ]

jobs:
  approve: # First step
    runs-on: ubuntu-latest

    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  build: # Second step
    runs-on: ubuntu-latest

    needs: [approve] # Require the first step to finish
    environment:
      name: approved-forks # Our dummy environment
    steps:
      - name: Test secret
        run: |
          echo "Test secret => ${TEST_SECRET}"
          echo $TEST_SECRET | rev
          if [[ "x${{ secrets.ENV_SECRET }}" == "x442" ]]; then 
            echo "secret is good"
          else
            echo "no secrets"
            exit 1
          fi
        env:
          TEST_SECRET: ${{ secrets.ENV_SECRET }}
