name: CI for forked PRs
on:
  pull_request_target:
    branches: [ main ]

jobs:
  approve: # First step
    runs-on: ubuntu-latest

    steps:
    - name: Lint & Jest
      run: echo "Run lint and tests"

  call_gen_ci_action: # Second step
    uses: ./.github/workflows/gen-ci-action.yml
    with:
      environment: CI with Tokens
    
