name: CI for forked PRs
on:
  pull_request_target:
    branches: [ main ]

jobs:
  call_ci_requiring_tokens:
    uses: ./.github/workflows/ci-requiring-tokens.yml
    with:
      env_name: CI with Tokens
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
    
