name: CI Builds requiring mapbox tokens

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
        default: default
      ref:
        required: false
        type: string
    secrets:
      MAPBOX_ACCESS_TOKEN:
        required: false
      MAPBOX_DOWNLOAD_TOKEN:
        required: false

concurrency: 
  group: ${{ github.head_ref || github.run_id }}-ci-with-tokens
  cancel-in-progress: true

jobs:
  call_android_workflow:
    name: "Android/Mapbox"
    uses: ./.github/workflows/android-actions.yml
    with:
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
