name: Reuseable CI action

on:
  workflow_call:
    inputs:
      env_name:
        default: default
        required: false
        type: string
      ref:
        required: false
        type: string

jobs:
  build:
    name: "Run CI test"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ inputs.ref == '' }}
      - name: Checkout/ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
        if: ${{ inputs.ref != '' }}
      - name: Test environent:
        run:
          echo "ENV name: ${{ inputs.env_name }}"
      - name: Test README
        run: cat README.md
      - name: Test secret
        run: |
          echo "Test secret => ${TEST_SECRET}"
          echo $TEST_SECRET | rev
          if [[ "x${{ secrets.ENV_SECRET }}" == "x442" ]]; then 
            echo "secret is good"
          else
            echo "no secrets"
            exit 1
          fi
        env:
          TEST_SECRET: ${{ secrets.ENV_SECRET }}
        
